[env]
_.path = [
  "{{env.XDG_CONFIG_HOME}}/vite-plus/bin",
  "node_modules/.bin",
  "node_modules/.pnpm/node_modules/.bin",
]

[settings]
lockfile = true

[tools]
"npm:@commitlint/cli" = "latest"
actionlint = "latest"
editorconfig-checker = "latest"
ghalint = "latest"
hk = "latest"
python = "latest"
shellcheck = "latest"
uv = "latest"
zizmor = "latest"

[tools.yamllint]
version = "latest"
depends = ["python", "uv"]
