[env]
_.path = ["~/.vite-plus/bin", "node_modules/.bin", "node_modules/.pnpm/node_modules/.bin"]

[settings]
lockfile = true

[tools]
editorconfig-checker = "latest"
pnpm = "latest"
python = "latest"
uv = "latest"

[tools.yamllint]
version = "latest"
depends = ["python", "uv"]
