[env]
_.path = [
  "{{env.XDG_CONFIG_HOME}}/vite-plus/bin",
  "node_modules/.bin",
  "node_modules/.pnpm/node_modules/.bin",
]

[tools]
"aqua:owenlamont/ryl" = "latest"
"npm:@commitlint/cli" = "latest"
actionlint = "latest"
editorconfig-checker = "latest"
ghalint = "latest"
hk = "latest"
shellcheck = "latest"
zizmor = "latest"
