packages:
  - packages/*
allowBuilds:
  esbuild: true
  spawn-sync: true

catalog:
  "@commitlint/cli": 20.5.0
  "@commitlint/config-conventional": 20.5.0
  "@tsconfig/strictest": 2.0.8
  "@types/node": 24.12.0
  typescript: 5.9.3
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: 0.1.12
  vitest: npm:@voidzero-dev/vite-plus-test@latest
catalogMode: prefer
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
