packages:
  - packages/*
allowBuilds:
  esbuild: true
  spawn-sync: true
catalog:
  "@commitlint/cli": 21.2.1
  "@commitlint/config-conventional": 21.2.0
  "@commitlint/types": 21.2.0
  "@tsconfig/strictest": 2.0.8
  "@types/node": 24.13.3
  "@wxt-dev/storage": ^1.2.8
  typescript: 6.0.3
  vite: npm:@voidzero-dev/vite-plus-core@0.2.4
  vite-plus: 0.2.4
  vitest: npm:@voidzero-dev/vite-plus-test@0.1.24
  wxt: 0.20.27
catalogMode: prefer
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
