packages:
  - packages/*
allowBuilds:
  esbuild: true
  spawn-sync: true
catalog:
  "@tsconfig/strictest": 2.0.8
  "@types/node": 24.13.5
  "@wxt-dev/storage": ^1.2.9
  typescript: 7.0.2
  vite: npm:@voidzero-dev/vite-plus-core@0.3.2
  vite-plus: 0.3.2
  wxt: 0.21.4
catalogMode: prefer
overrides:
  vite: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
